### ISSUE TITLE
Getting error when trying to access IceCat Bundle 3.0.0 in Pimcore

### ISSUE THREAD

**Issue by syncrasy-git** [IcecatNV/Icecat-Integration#13]
I have upgraded from IceCat Bundle 2 to 3.0.0, however getting following error when trying to access the bundle in Pimcore 10.5.14.

Error: An exception occurred while executing 'SELECT * FROM icecat_recurring_import WHERE status = 'finished'': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.icecat_recurring_import' doesn't exist

**Comment by IcecatNV** [comment]
Hi Raj, We have tested the 3.0.0 on the Pimcore 10.2.x version. Since you are using Pimcore 10.5.14 version and so looking at the error, it seems that the table  'pimcore.icecat_recurring_import' hasn't been created on 10.5.14 version.  You could try following two options:
1. Configure the automated recurring job once (if not already done) and see if the table is then created.
2. Try creating the table manually.

**Comment by syncrasy-git** [comment]
Although I could install v3.0.0 in Pimcore 10.5.14 and could import few products, however I am facing strange issue, in every few minutes Pimcore stops responding and gives error 503, and this seems to be due the polling.

`The timeout specified has expired: [client 122.161.49.66:10045] AH01075: Error dispatching request to : (polling)`

**Comment by IcecatNV** [comment]
Hi @syncrasy-git 

We have fixed the charset collation for the above recurring table and released a new V4.0.0 version. The V4 will work on Pimcore version 10.5.* 

Please test and confirm once the issue has been resolved at your end so that then I will close this issue.
